### ISSUE TITLE
Updating the assets?

### ISSUE THREAD

**Issue by OmitLeChuck** [Griboedow/SwaggerDoc#1]
Hello @Griboedow ,

this is a great extension and I also like to use it, but it would be really wonderful if there could be an update regarding the assets (swagger css and js).
I have already tried this myself by copying the current files from the swagger repo ( [swagger-ui](https://github.com/swagger-api/swagger-ui/tree/master/dist) ) into the extension, but the result is that nothing is displayed anymore.
I guess that something has to be adjusted somewhere.

Can you help?

**Comment by Griboedow** [comment]
Hi! I am glad the extension is useful for you. I will check this week, probably should be easy

**Comment by Griboedow** [comment]
Updated in 7b7d5e9b59463dd81402850a6643eb20b14c948e


Looks like works out of the box. I have updated 

- swagger-ui.css
- swagger-ui-bundle.js
- swagger-ui-standalone-preset.js

To the latest version

**Comment by Griboedow** [comment]
Works well on my test env. 

![image](https://user-images.githubusercontent.com/4194526/213917374-2439ea2d-d0cd-4a81-9e29-a48af6a9ffc1.png)

**Comment by Griboedow** [comment]
Ah, my bad,  Isee the issue. It is not fully working with new files indeed.

**Comment by Griboedow** [comment]
I see that v3 is loading fine, but v4 for some reason cannot be loaded via mediwaiki resourceLoader.

**Comment by Griboedow** [comment]
Finally fixed in d6df3e013314cfdb1449033dfe50c5b59cb60a7b

There was a stupid arror on my side: remoteExtPath was doubled. 
++ We had to createswaggerDoc using "window.ui = <..>" instead of "const ui = <..>"

Tip for other who might be debugging any extension, add "?debug=true" to see the loading errors. I could save a lot of time on that :D

**Comment by Griboedow** [comment]
Looks liek initial commit was still not working without ebug.

The problem was that ResourceLoader minifies JS by default. And minification works bad for 4.15 code. 

Resolved by adding `/*@nomin*/` instruction to all external js files.
