### ISSUE TITLE
Readme update: Short urls

### ISSUE THREAD

**Issue by mattsmith321** [Griboedow/SwaggerDoc#3]
I just configured this SwaggerDoc extension on our internal MediaWiki instance running MediaWiki 1.31. Everything worked fine with one little hiccup.

Per https://www.mediawiki.org/wiki/Manual:Parameters_to_index.php#Raw, in order to reference a url with action=raw, you must use the script path, and not the short / pretty url to the Swagger spec.

In my case, the short / pretty url to the Swagger spec is:
  http://wiki.example.com/wiki/MyWebApi_Swagger_spec

In order to get it to work, I had to use:
  http://wiki.example.com/w/index.php?title=MyWebApi_Swagger_spec&action=raw

Would be good to add a note to the readme to help other people out that might run into the same situation.

**Comment by Griboedow** [comment]
Hi!

Yep, that is correct. That format was used in the example in Readme. I've explained it a bit more in details in the latest readme
